services:
  postgres:
    image: 'postgres:17'
    container_name: "gig-pass-postgress"
    env_file:
      - src/main/resources/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
#    healthcheck:
#      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}'"]
#      interval: 10s
#      timeout: 3s
#      retries: 3

volumes:
  postgres_data: